title: Enter Activation Pin or Code : Spotify Pair
description: Spotify connect is a feature of Spotify which allows you to use it as a remote control and to cast content to other devices in your home.To control the Spotify app on the smartphone, all devices must be connected to the same Wi Fi network.
Footer
